export const ANSWER_REPOSITORY = 'ANSWER_REPOSITORY';
export const COURSE_REPOSITORY = 'COURSE_REPOSITORY';
export const EXAMPLE_REPOSITORY = 'EXAMPLE_REPOSITORY';
export const PATTERNINSTANCE_REPOSITORY = 'PATTERNINSTANCE_REPOSITORY';
export const PATTERNTEMPLATE_REPOSITORY = 'PATTERNTEMPLATE_REPOSITORY';
